# Generated by Django 5.0 on 2023-12-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
